services:
  # Backend Service
  - type: web
    name: project-vepr
    env: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm run start
    rootDir: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: project-vepr
          property: port
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: FRONTEND_URL
        fromService:
          type: web
          name: project-vepr-frontend
          property: url
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  # Frontend Service
  - type: web
    name: project-vepr-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_API_URL
        fromService:
          type: web
          name: project-vepr
          property: url